### ISSUE TITLE
event-emitter breaking change with version 2.0.0

### ISSUE THREAD

**Issue by joanbarros** [PigottConsulting/robust-queue#2]
Seems that there has been a breaking change in the `event-emitter` package with version `2.0.0` and avove that broke something in `robust-queue`.

## Error
I'm getting the following error when initializing:
```console
C:\dev\oss\robust-queue\node_modules\eventemitter3\index.js:179
  if (!this._events[evt]) this._events[evt] = listener, this._eventsCount++;
                   ^

TypeError: Cannot read property 'error' of undefined
    at Queue.on (C:\dev\oss\robust-queue\node_modules\eventemitter3\index.js:179:20)
    at new Queue (C:\dev\oss\robust-queue\index.js:24:10)
    at Object.<anonymous> (C:\dev\oss\robust-queue\test.js:2:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

## Reproducing
Run the initializing code:
```javascript
var Queue = require('robust-queue');
var q = new Queue();
```

## Solution
An immediate solution is to roll back the version of `event-emitter` used to `^1.0.0`.

I could provide a PR but this change is trivial enough. Let me know if further assistance is needed with this issue.

**Comment by westinpigott** [comment]
I capped the version to below 2.  I was able to reproduce, and once version is capped below 2.0.0, it is working.

**Comment by joanbarros** [comment]
Thnx! Working perfectly now 👌
